# Generated by Django 4.0.5 on 2022-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('monthly_stipend', models.IntegerField()),
                ('weekly_stipend', models.IntegerField()),
                ('incentives', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('last_date_to_apply', models.DateField()),
                ('applicants_count', models.IntegerField()),
                ('openings', models.IntegerField()),
                ('skills', models.CharField(max_length=300)),
                ('perks', models.CharField(max_length=300)),
                ('src_url', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
