# Generated by Django 4.0.5 on 2022-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_openings_internshipdetail_number_of_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipdetail',
            name='incentives',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='internshipdetail',
            name='last_date_to_apply',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='internshipdetail',
            name='monthly_stipend',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='internshipdetail',
            name='perks',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='internshipdetail',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='internshipdetail',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='internshipdetail',
            name='weekly_stipend',
            field=models.IntegerField(null=True),
        ),
    ]
