# Generated by Django 4.0.5 on 2022-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_internshipdetail_incentives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipdetail',
            name='number_of_openings',
            field=models.IntegerField(null=True),
        ),
    ]
